# nicksha@mbookair

general.import = [
    "~/.config/alacritty/themes/rose-pine.toml"
    # "~/.config/alacritty/themes/vague.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

startup_mode = "Maximized"

opacity = 1

decorations = "Buttonless"

option_as_alt = "Both"

[mouse]
hide_when_typing = true

[font]
size = 24

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
